name: Android CI - Build APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: # allows manual trigger from Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout source code
      - name: Checkout
        uses: actions/checkout@v4

      # 2️⃣ Set up JDK for Android build
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      # 3️⃣ Give execute permission to Gradle wrapper
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # 4️⃣ Cache Gradle dependencies (faster builds)
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 5️⃣ Build Debug APK
      - name: Build Debug APK
        run: ./gradlew clean assembleDebug --stacktrace

      # 6️⃣ Run Lint checks (optional)
      - name: Run Lint checks
        run: ./gradlew lintDebug

      # 7️⃣ Upload generated APK as artifact
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: Wifistrength-debug-apk
          path: app/build/outputs/apk/debug/app-de
